# Generated by Django 5.2.5 on 2025-09-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='certifications/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
